### ISSUE TITLE
Question  - Warning message

### ISSUE THREAD

**Issue by bobhenl** [LinoxGH/MoreTools#14]
Hi, I'm getting this warning in console, do you think that you could fix it?
```
[05:07:05] [Server thread/WARN]: [MoreTools] =================================================
[05:07:05] [Server thread/WARN]: [MoreTools] MoreTools is using a deprecated version of
[05:07:05] [Server thread/WARN]: [MoreTools] bStats which is bundled with Slimefun.
[05:07:05] [Server thread/WARN]: [MoreTools] Future versions will not include this file anymore.
[05:07:05] [Server thread/WARN]: [MoreTools] MoreTools needs to be updated as soon as possible.
[05:07:05] [Server thread/WARN]: [MoreTools] =================================================
```

Reported also to author of extraTools and got this reply https://github.com/Sfiguz7/ExtraTools/issues/13.

**Comment by bobhenl** [comment]
```
[23:14:02] [Server thread/INFO]: [MoreTools] Enabling MoreTools vDEV - 8 (git db8d8814)
[23:14:02] [Server thread/INFO]: [MoreTools] Setting up event metrics...
[23:14:02] [Server thread/ERROR]: Error occurred while enabling MoreTools vDEV - 8 (git db8d8814) (Is it up to date?)
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/bstats/bukkit/Metrics
	at io.github.linoxgh.moretools.MoreTools.onEnable(MoreTools.java:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.bstats.bukkit.Metrics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-320]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
	... 11 more
```

**Comment by bobhenl** [comment]
@LinoxGH ?

**Comment by LinoxGH** [comment]
Should be fixed in the next version. Reopen if it persists.
