### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by TheRealM18** [LinoxGH/MoreTools#15]
## Description (Required)
On server start, the plugin will not start, as it is having an issue with a NoSuchMethodError.

## Steps to reproduce the Issue (Required)
![image](https://user-images.githubusercontent.com/5025664/104229725-00dcf000-5423-11eb-8f8a-878d042cd0b5.png)

## Expected behavior (Required)
To Enable

## Server Log / Error Report
https://pastebin.com/D6CG5KM3

## Environment (Required)
Java 11

 - Minecraft Version:
 - CS-CoreLib Version: 92
 - Slimefun Version: 780
 - Plugin Version: 9

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Hello,

I have the same problem

```

[05:13:34] [Server thread/INFO]: [MoreTools] Enabling MoreTools vDEV - 9 (git e8cfb32c)
--
1622 | [05:13:34] [Server thread/INFO]: [MoreTools] Setting up event listeners...
1623 | [05:13:34] [Server thread/INFO]: [MoreTools] Setting up categories...
1624 | [05:13:34] [Server thread/INFO]: [MoreTools] Setting up items...
1625 | [05:13:34] [Server thread/ERROR]: Error occurred while enabling MoreTools vDEV - 9 (git e8cfb32c) (Is it up to date?)
1626 | java.lang.NoSuchMethodError: 'io.github.thebusybiscuit.slimefun4.core.services.plugins.ThirdPartyPluginService io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.getThirdPartySupportService()'
1627 | at io.github.linoxgh.moretools.items.CrescentHammer.<init>(CrescentHammer.java:57) ~[?:?]
1628 | at io.github.linoxgh.moretools.MoreTools.setupItems(MoreTools.java:101) ~[?:?]
1629 | at io.github.linoxgh.moretools.MoreTools.onEnable(MoreTools.java:83) ~[?:?]
1630 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-253]
1631 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-253]
1632 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-253]
1633 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-253]
1634 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-253]
1635 | at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-253]
1636 | at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-253]
1637 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-253]
1638 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
1639 | at java.lang.Thread.run(Thread.java:834) [?:?]
1640 | [05:13:34] [Server thread/INFO]: [MoreTools] Disabling MoreTools vDEV - 9 (git e8cfb32c)


```

**Comment by LinoxGH** [comment]
I believe this issue is now fixed. Reopen if it persists.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
It loads now... Yes but there is only one tool as default inside. It is normal? Do we have to create the tools?

**Comment by LinoxGH** [comment]
> It loads now... Yes but there is only one tool as default inside. It is normal? Do we have to create the tools?

Yes it is. This addon currently consists of 1 tool.
