### ISSUE TITLE
Plugin not loading. (Yet another CS-CoreLib dep. issue)

### ISSUE THREAD

**Issue by MagmaSlime123** [LinoxGH/MoreTools#17]
## Description (Required)
Plugin fails to load. Yet another Cs-CoreLib dep. issue I think.

## Steps to reproduce the Issue (Required)
Use the plugin.

## Expected behavior (Required)
It to load.

## Server Log / Error Report
https://pastebin.com/QcVQs98b

## Environment (Required)
![2021-01-24_16 05 50](https://user-images.githubusercontent.com/51277766/105648199-18729a80-5e5f-11eb-9917-2b3f0a35acf6.png)
![2021-01-24_16 05 55](https://user-images.githubusercontent.com/51277766/105648201-19a3c780-5e5f-11eb-8391-238172526e5e.png)

**Comment by bobhenl** [comment]
Isn't it due to this?
```
[17:39:10] [Server thread/ERROR]: Error occurred while enabling MoreTools vDEV - 9 (git e8cfb32c) (Is it up to date?)
java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.implementation.SlimefunPlugin.getThirdPartySupportService()Lio/github/thebusybiscuit/slimefun4/core/services/plugins/ThirdPartyPluginService;
	at io.github.linoxgh.moretools.items.CrescentHammer.<init>(CrescentHammer.java:57) ~[?:?]
	at io.github.linoxgh.moretools.MoreTools.setupItems(MoreTools.java:101) ~[?:?]
	at io.github.linoxgh.moretools.MoreTools.onEnable(MoreTools.java:83) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:259) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by mrcoffee1026** [comment]
Confirmed: MoreTools vDEV - 9 (git e8cfb32c)
Paper git-Paper-470 (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
